services:
  gifts-buyer:
    build: .
    container_name: gifts-buyer
    volumes:
      - ./config.ini:/app/config.ini
      - ./data:/app/data
      - ./locales:/app/locales
    environment:
      - TZ=UTC
    restart: on-failure:3
